title: "BaiYunfeng 的个人网站"
description: "欢迎访问我的个人主页"
baseurl: "" # 保持为空
url: "https://BaiYunfeng.github.io"

# 社交链接
github_username: BaiYunfeng
twitter_username: your_twitter

# 主题设置
theme: jekyll-theme-minimal
